# General

[env]
TERM = "xterm-256color"

[window]
padding.x = 2
padding.y = 0
decorations = "Buttonless"
opacity = 0.9
blur = true
startup_mode = "SimpleFullscreen" # Other options: "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font" # Other options: "JetBrains Mono Nerd Font", "MesloLG Nerd Font"
size = 16
